#!/bin/bash

function install() {
  local version=$1

  if [[ $version = "" ]]; then
    version="8.2.0940"
  fi

  local script_path=$(dirname $(realpath -s $0))
  local tmp_path=$(realpath $script_path/../../tmp)
  local download_url="https://github.com/vim/vim/archive/v${version}.tar.gz"

  echo "installing vim, environment:"
  echo "    script path: ${script_path}"
  echo "       tmp path: ${tmp_path}"
  echo "    vim version: ${version}"
  echo "   download url: ${download_url}"
  echo ""
  echo "preparing to downloading vim from '${download_url}' (from ${script_path})"

  read -p "look good? " continue_install

  if [[ "${continue_install}" != "yes" ]]; then
    echo "not ready, bailing out - ${continue_install}"
    return
  fi

  echo "continuing installation w/ ${continue_install}"

  if [[ -d $tmp_path ]]; then
    echo "found tmp dir, clearing"
    rm -rf $tmp_path
  fi

  mkdir -p $tmp_path
  curl -L --output $tmp_path/vim.tar.gz $download_url

  echo "download complete, moving into '$tmp_path'"
  pushd $tmp_path

  tar xvzf vim.tar.gz
  local source_dir="vim-$version"
  echo "extract complete, moving into '$source_dir'"
  pushd $source_dir

  echo "configuring vim..."
  ./configure --enable-pythoninterp=yes --enable-python3interp=yes --with-compiledby='dadleyy/vimfiles'
  echo "configuration complete, compiling"
  make

  read -p "vim compiled and ready for install, continue? " continue_install

  if [[ "${continue_install}" != "yes" ]]; then
    echo "not ready, bailing out"
    popd
    popd
    return
  fi

  sudo make install

  echo "leaving build dir"
  popd
  popd
  echo "cleaning up"
  rm -rf $tmp_path
}

install $@
