#!/bin/zsh

sizethree_prompt() {
  local reset='%f'
  local yellow='%F{3}'
  local green='%F{2}'
  local part_delim=" › "
  local host_info=""
  local battery_info=""

  local current_dir="$(pwd)"
  local name=$(uname)
  local branch_name="$(git symbolic-ref --short HEAD 2> /dev/null)"
  local context="$(basename $current_dir)"

  if [[ -f "${HOME}/.config/dadleyy/host-info" ]]; then
    host_info="[$(cat "${HOME}/.config/dadleyy/host-info")]"
  fi

  if [[ "Darwin" == $name && $(which battrs) != "" ]]; then
    local percent="$(battrs)"

    if [[ "" != "${percent}" ]]; then
      battery_info="${percent} "
    fi
  fi

  if [[ "" == "${branch_name}" ]]; then
    PS1="$host_info$battery_info> "
    return
  fi

  local dest="$(git ls-remote --get-url 2> /dev/null | sed -E "s/^(git@github.com:|^git@bitbucket.org:)(.*)\.git/\2/")"

  if [[ "" != "${dest}" ]]; then
    context="${dest}"
  fi

  local change_color=${green}
  local changes="$(git diff-index --name-only HEAD -- 2> /dev/null)"

  if [[ "" != "${changes}" ]];
  then
    change_color=${yellow}
    part_delim=" ± "
  fi

  PROMPT="$host_info$battery_info(${context}${part_delim}${change_color}${branch_name}${reset}) "
}
